name: Staging Cannons
description: Push out results

on:
  push:
    branches:
      - staging

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Squawk
        run: echo "Squawk again!"