name: Staging Cannons
description: Push out results

on:
  push:
    branches:
      - staging
      - fix/stillbroken
permissions:
  contents: write
  pull-requests: write

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Squawk
        run: echo "Squawk again!"
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Variables
        id: vars
        shell: bash  
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          RCI="rc-${COMMIT_HASH}"
          NEXT_BRANCH="review"
          echo "rci=$RCI" >> "$GITHUB_OUTPUT"
          echo "next_branch=$NEXT_BRANCH" >> "$GITHUB_OUTPUT"
      - name: Tag commit with RCI
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git tag ${{ steps.vars.outputs.rci }}
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin ${{ steps.vars.outputs.rci }}
        env:
          GH_TOKEN: ${{ secrets.PR_TOKEN }}
      - name: Create PR To Review
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_TOKEN }}
          branch: promote/review/${{ steps.vars.outputs.rci }}
          base: ${{ steps.vars.outputs.next_branch }}
          title: "Promote RCI ${{ steps.vars.outputs.rci }} to ${{ steps.vars.outputs.next_branch }}"
          body: |
            Automated promotion of RCI `${{ steps.vars.outputs.rci }}` from `${{ github.ref_name }}` to `${{ steps.vars.outputs.next_branch }}`.
            Commit: `${{ github.sha }}`